---
- platform: template
  switches:
    vacuum:
      friendly_name: Staubsauger
      value_template: "{{ is_state('vacuum.roborock', 'on') }}"
      turn_on:
        service: vacuum.turn_on
        entity_id: vacuum.roborock
      turn_off:
        service: vacuum.return_to_base
        entity_id: vacuum.roborock
