---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-red-internal
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/target: "k8s.lan.aomame.de"
spec:
  tls:
    - secretName: lan-aomame-de-tls
      hosts:
        - nodered.lan.aomame.de
  rules:
    - host: nodered.lan.aomame.de
      http:
        paths:
          - backend:
              serviceName: node-red
              servicePort: 1880
