---
language: python
python:
  - "3.6"
install:
  - pip3 install homeassistant yamllint
before_script:
  - mv travis_secrets.yaml secrets.yaml
  - export $(cat .env.travis | xargs)
script:
  - hass -c . --script check_config
  - yamllint .
