---
language: python
python:
  - "3.6"
env:
  - DATABASE_URL=mysql://user:password@SERVER_IP/DB_NAME?charset=utf8
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant yamllint
script:
  - hass -c . --script check_config
  - yamllint .
