---
language: python
python:
  - "3.6"
env:
  global:
    - HTTP_PASSWORD=supersecret
    - DATABASE_URL=mysql://user:password@SERVER_IP/DB_NAME?charset=utf8
    - VACUUM_TOKEN=e0000000000000000000000000000000
    - DARK_SKY_API_TOKEN=e0000000000000000000000000000000
    - SPOTIFY_ID=e0000000000000000000000000000000
    - SPOTIFY_SECRET=e0000000000000000000000000000000
    - MQTT_PASSWORD=supersecret
    - INFLUXDB_USERNAME=user
    - INFLUXDB_PASSWORD=supersecret
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant yamllint
script:
  - hass -c . --script check_config
  - yamllint .
