---
language: python
python:
  - "3.6"
install:
  - pip3 install homeassistant yamllint
before_script:
  - mv travis_secrets.yaml secrets.yaml
script:
  - source .env.travis
  - hass -c . --script check_config
  - yamllint .
