---
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes
config:
api:
websocket_api:
http:
  base_url: https://hass.lan.aomame.de

system_health:
updater:
zeroconf:
mobile_app:
person:
map:
sun:

tts:
  - platform: google_translate
    service_name: google_say
    language: de

cloud:
  alexa:
    filter:
      include_entities:
        - sensor.aqara_sensor_1_temperature
        - sensor.aqara_sensor_2_temperature
        - sensor.aqara_sensor_3_temperature
        - sensor.aqara_sensor_4_temperature
        - sensor.aqara_sensor_5_temperature
        - switch.vacuum
        - switch.tv
      include_domains:
        - scene
        - light
    entity_config:
      sensor.aqara_sensor_1_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_2_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_3_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_4_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_5_temperature:
        display_categories: TEMPERATURE_SENSOR
      switch.vacuum:
        display_categories: OTHER
      switch.tv:
        display_categories: TV

discovery:
  ignore:
    - apple_tv
    - google_cast
    - sonos

logger:
  default: warn

recorder:
  db_url: !env_var DATABASE_URL
  purge_keep_days: 30
  exclude:
    domains:
      - weather
    entities:
      - sun.sun
      - automation.update_notifications
      - sensor.iphone_x_von_felix_triller_battery_level
      - sensor.iphone_x_von_felix_triller_battery_state
      - sensor.last_boot
      - switch.vacuum
      - sensor.ssid

history:
  exclude:
    domains:
      - group

logbook:
  include:
    domains:
      - light
      - switch
      - media_player
      - vacuum
      - device_tracker
    entities:
      - sensor.latest_hass_version
  exclude:
    entities:
      - switch.vacuum

mqtt:
  broker: mosquitto
  username: homeassistant
  password: !env_var MQTT_PASSWORD
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

influxdb:
  host: influxdb
  username: !env_var INFLUXDB_USERNAME
  password: !env_var INFLUXDB_PASSWORD
  database: home_assistant
  include:
    entities:
      - sensor.aqara_sensor_1_humidity
      - sensor.aqara_sensor_1_pressure
      - sensor.aqara_sensor_1_temperature
      - sensor.aqara_sensor_2_humidity
      - sensor.aqara_sensor_2_pressure
      - sensor.aqara_sensor_2_temperature
      - sensor.aqara_sensor_3_temperature
      - sensor.aqara_sensor_3_humidity
      - sensor.aqara_sensor_3_pressure
      - sensor.aqara_sensor_4_temperature
      - sensor.aqara_sensor_4_humidity
      - sensor.aqara_sensor_4_pressure
      - sensor.aqara_sensor_5_temperature
      - sensor.aqara_sensor_5_humidity
      - sensor.aqara_sensor_5_pressure
      - sensor.aqara_sensor_6_temperature
      - sensor.aqara_sensor_6_humidity
      - sensor.aqara_sensor_6_pressure
      - binary_sensor.aqara_door_1_battery
      - binary_sensor.aqara_door_3_battery
      - binary_sensor.aqara_door_4_battery
      - sensor.darksky_humidity
      - sensor.darksky_pressure
      - sensor.darksky_temperature
      - sensor.tradfri_remote_control
      - sensor.tradfri_remote_control_2
      - sensor.tradfri_remote_control_3
      - sensor.rheinpegel

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.9
    token: !env_var VACUUM_TOKEN
    name: Roborock

media_player:
  - platform: spotify
    client_id: !env_var SPOTIFY_ID
    client_secret: !env_var SPOTIFY_SECRET

homekit:
  filter:
    include_entities:
      - switch.vacuum
      - switch.tv
      - switch.osram_plug_1
      - input_boolean.someone_home
      - light.lichterkette_kinderzimmer
      - light.weihnachtsbaum
      - sensor.aqara_sensor_1_humidity
      - sensor.aqara_sensor_1_temperature
      - sensor.aqara_sensor_2_humidity
      - sensor.aqara_sensor_2_temperature
      - sensor.aqara_sensor_3_humidity
      - sensor.aqara_sensor_3_temperature
      - sensor.aqara_sensor_4_humidity
      - sensor.aqara_sensor_4_temperature
      - sensor.aqara_sensor_5_humidity
      - sensor.aqara_sensor_5_temperature
      - sensor.aqara_sensor_6_humidity
      - sensor.aqara_sensor_6_temperature

weather:
  - platform: darksky
    api_key: !env_var DARK_SKY_API_TOKEN
    mode: daily

automation: !include automations.yaml
group: !include_dir_merge_named groups
input_boolean: !include_dir_merge_named input_booleans
light: !include_dir_merge_list lights
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
timer: !include_dir_merge_named timers
zone: !include_dir_merge_list zones
