---
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

frontend:
config:
api:
websocket_api:
http:
  api_password: !env_var HTTP_PASSWORD
  base_url: https://hass.aomame.de
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.178.3
  ip_ban_enabled: false
  login_attempts_threshold: 3

map:
sun:
ios:

cloud:
  alexa:
    filter:
      include_entities:
        - sensor.aqara_sensor_1_temperature
        - sensor.aqara_sensor_2_temperature
        - sensor.aqara_sensor_3_temperature
        - sensor.aqara_sensor_4_temperature
        - switch.vacuum
      include_domains:
        - scene
    entity_config:
      sensor.aqara_sensor_1_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_2_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_3_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_4_temperature:
        display_categories: TEMPERATURE_SENSOR
      switch.vacuum:
        display_categories: OTHER

discovery:
  ignore:
    - apple_tv
    - google_cast
    - sonos
    - igd

logger:
  default: warn

recorder:
  db_url: !env_var DATABASE_URL
  purge_keep_days: 30
  exclude:
    domains:
      - weather
    entities:
      - sun.sun
      - automation.update_notifications
      - sensor.iphone_x_von_felix_triller_battery_level
      - sensor.iphone_x_von_felix_triller_battery_state
      - sensor.last_boot
      - switch.vacuum

history:
  exclude:
    domains:
      - group

logbook:
  include:
    domains:
      - light
      - switch
      - media_player
      - vacuum
      - device_tracker
    entities:
      - sensor.latest_hass_version
  exclude:
    entities:
      - switch.vacuum

mqtt:
  broker: mosquitto
  username: homeassistant
  password: !env_var MQTT_PASSWORD
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

notify:
  - name: pushover
    platform: pushover
    api_key: !env_var PUSHOVER_API_KEY
    user_key: !env_var PUSHOVER_USER_KEY

influxdb:
  host: influxdb
  username: !env_var INFLUXDB_USERNAME
  password: !env_var INFLUXDB_PASSWORD
  database: home_assistant
  include:
    entities:
      - binary_sensor.aqara_door_1
      - sensor.aqara_sensor_1_humidity
      - sensor.aqara_sensor_1_pressure
      - sensor.aqara_sensor_1_temperature
      - sensor.aqara_sensor_2_humidity
      - sensor.aqara_sensor_2_pressure
      - sensor.aqara_sensor_2_temperature
      - sensor.aqara_sensor_3_temperature
      - sensor.aqara_sensor_3_humidity
      - sensor.aqara_sensor_3_pressure
      - sensor.aqara_sensor_4_temperature
      - sensor.aqara_sensor_4_humidity
      - sensor.aqara_sensor_4_pressure
      - sensor.aqara_sensor_5_temperature
      - sensor.aqara_sensor_5_humidity
      - sensor.aqara_sensor_5_pressure
      - sensor.aqara_sensor_6_temperature
      - sensor.aqara_sensor_6_humidity
      - sensor.aqara_sensor_6_pressure
      - sensor.darksky_humidity
      - sensor.darksky_pressure
      - sensor.darksky_temperature
      - sensor.tradfri_remote_control
      - sensor.tradfri_remote_control_2
      - sensor.tradfri_remote_control_3
      - sensor.innr_sp_120_watts
      - sensor.innr_sp_120_kwh
      - sensor.rheinpegel

deconz:
  host: 192.168.178.5

tradfri:
  host: 192.168.178.23
  allow_tradfri_groups: false

vacuum:
  - platform: xiaomi_miio
    host: 192.168.178.43
    token: !env_var VACUUM_TOKEN
    name: Roborock

sonos:
  media_player:
    hosts:
      - 192.168.178.31
      - 192.168.178.32

media_player:
  - platform: spotify
    client_id: !env_var SPOTIFY_ID
    client_secret: !env_var SPOTIFY_SECRET

homekit:
  filter:
    include_entities:
      - switch.osram_plug_1

weather:
  - platform: darksky_daily
    api_key: !env_var DARK_SKY_API_TOKEN

group: !include_dir_merge_named groups
sensor: !include_dir_merge_list sensors
automation: !include_dir_merge_list automations
switch: !include_dir_merge_list switches
zone: !include_dir_merge_list zones
input_boolean: !include_dir_merge_named input_booleans
timer: !include_dir_merge_named timers
scene: !include_dir_merge_list scenes
