---
homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
  auth_providers:
    - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes
config:
api:
websocket_api:
http:

system_health:
updater:
zeroconf:
mobile_app:
ios:
person:
map:
sun:
webhook:

tts:
  - platform: google_cloud
    key_file: /root/.gcs_key.json
    voice: de-DE-Wavenet-B
    encoding: linear16

cloud:
  alexa:
    filter:
      include_entities:
        - sensor.aqara_sensor_1_temperature
        - sensor.aqara_sensor_2_temperature
        - sensor.aqara_sensor_3_temperature
        - sensor.aqara_sensor_4_temperature
        - sensor.aqara_sensor_5_temperature
        - sensor.aqara_sensor_6_temperature
        - sensor.aqara_sensor_7_temperature
        - sensor.aqara_sensor_8_temperature
        - switch.vacuum
        - switch.tv
        - cover.sunea_io
      include_domains:
        - scene
        - light
    entity_config:
      sensor.aqara_sensor_1_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_2_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_3_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_4_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_5_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_6_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_7_temperature:
        display_categories: TEMPERATURE_SENSOR
      sensor.aqara_sensor_8_temperature:
        display_categories: TEMPERATURE_SENSOR
      switch.vacuum:
        display_categories: OTHER
      switch.tv:
        display_categories: TV
      cover.sunea_io:
        display_categories: EXTERIOR_BLIND

discovery:
  ignore:
    - apple_tv
    - google_cast

logger:
  default: warn

recorder:
  db_url: !env_var DATABASE_URL
  purge_keep_days: 30
  exclude:
    domains:
      - weather
    entities:
      - sun.sun
      - automation.update_notifications
      - sensor.last_boot
      - sensor.iphone_von_felix_triller_ssid
      - sensor.iphone_von_felix_triller_battery_level
      - sensor.iphone_von_felix_triller_battery_state
      - sensor.next_sunrise
      - sensor.next_sunset
    event_types:
      - themes_updated

history:
  exclude:
    domains:
      - group

logbook:
  include:
    domains:
      - light
      - switch
      - media_player
      - vacuum
      - device_tracker
    entities:
      - sensor.latest_hass_version
  exclude:
    entities:
      - switch.vacuum

mqtt:
  broker: mosquitto
  username: homeassistant
  password: !env_var MQTT_PASSWORD
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

influxdb:
  host: influxdb
  username: !env_var INFLUXDB_USERNAME
  password: !env_var INFLUXDB_PASSWORD
  database: home_assistant
  include:
    entities:
      - sensor.aqara_sensor_1_humidity
      - sensor.aqara_sensor_1_pressure
      - sensor.aqara_sensor_1_temperature
      - sensor.aqara_sensor_2_humidity
      - sensor.aqara_sensor_2_pressure
      - sensor.aqara_sensor_2_temperature
      - sensor.aqara_sensor_3_temperature
      - sensor.aqara_sensor_3_humidity
      - sensor.aqara_sensor_3_pressure
      - sensor.aqara_sensor_4_temperature
      - sensor.aqara_sensor_4_humidity
      - sensor.aqara_sensor_4_pressure
      - sensor.aqara_sensor_5_temperature
      - sensor.aqara_sensor_5_humidity
      - sensor.aqara_sensor_5_pressure
      - sensor.aqara_sensor_6_temperature
      - sensor.aqara_sensor_6_humidity
      - sensor.aqara_sensor_6_pressure
      - sensor.darksky_humidity
      - sensor.darksky_pressure
      - sensor.darksky_temperature
      - sensor.rheinpegel

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.9
    token: !env_var VACUUM_TOKEN
    name: Roborock

spotify:
  client_id: !env_var SPOTIFY_ID
  client_secret: !env_var SPOTIFY_SECRET

homekit:
  name: Home Assistant Bridge
  filter:
    include_entities:
      - cover.sunea_io
      - vacuum.roborock
      - switch.tv
      - switch.osram_plug_1
      - input_boolean.someone_home
      - light.lichterkette_kinderzimmer
      - sensor.aqara_sensor_1_temperature
      - sensor.aqara_sensor_1_humidity
      - sensor.aqara_sensor_2_temperature
      - sensor.aqara_sensor_2_humidity
      - sensor.aqara_sensor_3_temperature
      - sensor.aqara_sensor_3_humidity
      - sensor.aqara_sensor_4_temperature
      - sensor.aqara_sensor_4_humidity
      - sensor.aqara_sensor_5_temperature
      - sensor.aqara_sensor_5_humidity
      - sensor.aqara_sensor_6_temperature
      - sensor.aqara_sensor_6_humidity
      - sensor.aqara_sensor_7_temperature
      - sensor.aqara_sensor_7_humidity
      - sensor.aqara_sensor_8_temperature
      - sensor.aqara_sensor_8_humidity
  entity_config:
    sensor.aqara_sensor_1_temperature:
      linked_battery_sensor: sensor.aqara_sensor_1_battery
    sensor.aqara_sensor_1_humidity:
      linked_battery_sensor: sensor.aqara_sensor_1_battery
    sensor.aqara_sensor_2_temperature:
      linked_battery_sensor: sensor.aqara_sensor_2_battery
    sensor.aqara_sensor_2_humidity:
      linked_battery_sensor: sensor.aqara_sensor_2_battery
    sensor.aqara_sensor_3_temperature:
      linked_battery_sensor: sensor.aqara_sensor_3_battery
    sensor.aqara_sensor_3_humidity:
      linked_battery_sensor: sensor.aqara_sensor_3_battery
    sensor.aqara_sensor_4_temperature:
      linked_battery_sensor: sensor.aqara_sensor_4_battery
    sensor.aqara_sensor_4_humidity:
      linked_battery_sensor: sensor.aqara_sensor_4_battery
    sensor.aqara_sensor_5_temperature:
      linked_battery_sensor: sensor.aqara_sensor_5_battery
    sensor.aqara_sensor_5_humidity:
      linked_battery_sensor: sensor.aqara_sensor_5_battery
    sensor.aqara_sensor_6_temperature:
      linked_battery_sensor: sensor.aqara_sensor_6_battery
    sensor.aqara_sensor_6_humidity:
      linked_battery_sensor: sensor.aqara_sensor_6_battery
    sensor.aqara_sensor_7_temperature:
      linked_battery_sensor: sensor.aqara_sensor_7_battery
    sensor.aqara_sensor_7_humidity:
      linked_battery_sensor: sensor.aqara_sensor_7_battery
    sensor.aqara_sensor_8_temperature:
      linked_battery_sensor: sensor.aqara_sensor_8_battery
    sensor.aqara_sensor_8_humidity:
      linked_battery_sensor: sensor.aqara_sensor_8_battery

weather:
  - platform: darksky
    api_key: !env_var DARK_SKY_API_TOKEN
    mode: daily
  - platform: openweathermap
    api_key: !env_var OPENWEATHERMAP_API_TOKEN
    mode: daily

home_connect:
  client_id: !env_var HOME_CONNECT_CLIENT_ID
  client_secret: !env_var HOME_CONNECT_CLIENT_SECRET

zigbee2mqtt_networkmap:

automation: !include automations.yaml
input_boolean: !include_dir_merge_named input_booleans
light: !include_dir_merge_list lights
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
timer: !include_dir_merge_named timers
