---
version: '3'
services:
  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.77.2
    restart: always
    network_mode: host
    volumes:
      - .:/config
      - /etc/localtime:/etc/localtime:ro
  deconz:
    image: marthoc/deconz
    restart: always
    volumes:
      - ../deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
    ports:
      - 8080:8080
      - 8443:8443
