---
title: Zuhause

resources:
  - url: /local/weather-card/weather-card.js?v=0
    type: js

excluded_entities:
  - switch.innr_sp_120

views:
  - title: Home
    id: home
    cards:
      - type: custom:weather-card
        title: Köln
        entity_weather: weather.dark_sky_daily
        entity_sun: sun.sun

      - type: entities
        title: Current weather
        entities:
          - sun.sun
          - entity: sensor.rheinpegel
            icon: mdi:waves

      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.tradfri_bulb_e14_ws_opal_400lm_2
          - light.tradfri_bulb_e27_cws_opal_600lm
          - light.tradfri_bulb_e27_ws_opal_980lm

      - type: entities
        title: Scenes
        show_header_toggle: false
        entities:
          - scene.good_morning
          - scene.good_evening
          - scene.good_bye

      - type: entities
        title: Climate
        entities:
          - sensor.darksky_temperature
          - sensor.darksky_humidity
          - sensor.darksky_pressure
          - type: divider
          - sensor.average_room_temperature
          - sensor.average_room_humidity
          - sensor.average_room_pressure
          - type: divider
          - sensor.aqara_sensor_1_temperature
          - sensor.aqara_sensor_2_temperature
          - sensor.aqara_sensor_3_temperature
          - sensor.aqara_sensor_4_temperature
          - sensor.aqara_sensor_5_temperature
          - sensor.aqara_sensor_6_temperature
          - sensor.aqara_sensor_1_humidity
          - sensor.aqara_sensor_2_humidity
          - sensor.aqara_sensor_3_humidity
          - sensor.aqara_sensor_4_humidity
          - sensor.aqara_sensor_5_humidity
          - sensor.aqara_sensor_6_humidity
          - sensor.aqara_sensor_1_pressure
          - sensor.aqara_sensor_2_pressure
          - sensor.aqara_sensor_3_pressure
          - sensor.aqara_sensor_4_pressure
          - sensor.aqara_sensor_5_pressure
          - sensor.aqara_sensor_6_pressure
          - type: divider
          - sensor.xiaomi_ble_1_temperature
          - sensor.xiaomi_ble_1_humidity

      - type: entities
        title: Switches
        show_header_toggle: false
        entities:
          - switch.osram_plug_1

      - type: entities
        title: Vacuum
        show_header_toggle: false
        entities:
          - vacuum.roborock
          - switch.vacuum

  - title: Monitoring
    id: monitoring
    cards:
      - type: entities
        title: Batteries
        entities:
          - sensor.tradfri_remote_control
          - sensor.tradfri_remote_control_2
          - sensor.tradfri_remote_control_3

      - type: entities
        title: System
        entities:
          - sensor.last_boot
          - sensor.current_hass_version

      - type: entities
        title: Power consumption
        entities:
          - sensor.innr_sp_120_kwh
          - sensor.innr_sp_120_watts

  - title: Media
    id: media
    cards:
      - type: media-control
        entity: media_player.kuche

      - type: media-control
        entity: media_player.wohnzimmer

      - type: media-control
        entity: media_player.spotify

      - type: media-control
        entity: media_player.kinderzimmer

  - title: Misc
    id: misc
    cards:
      - type: entities
        title: Zigbee
        show_header_toggle: false
        entities:
          - input_boolean.zigbee_permit_join
          - timer.zigbee_permit_join
          - sensor.bridge_state

      - type: entities
        title: Automation
        show_header_toggle: true
        entities:
          - automation.update_notifications

      - type: entities
        title: Zone
        show_header_toggle: true
        entities:
          - zone.home
