- platform: switch
  name: Lichterkette Kinderzimmer
  entity_id: switch.innr_plug_1
- platform: switch
  name: Küche
  entity_id: switch.osram_plug_2
- platform: switch
  name: Weihnachtsbaum
  entity_id: switch.osram_plug_4
