- platform: min_max
  name: Average room temperature
  type: mean
  entity_ids:
    - sensor.aqara_sensor_1_temperature
    - sensor.aqara_sensor_2_temperature
    - sensor.aqara_sensor_3_temperature
    - sensor.aqara_sensor_4_temperature
    - sensor.aqara_sensor_5_temperature
- platform: min_max
  name: Average room humidity
  type: mean
  entity_ids:
    - sensor.aqara_sensor_1_humidity
    - sensor.aqara_sensor_2_humidity
    - sensor.aqara_sensor_3_humidity
    - sensor.aqara_sensor_4_humidity
    - sensor.aqara_sensor_5_humidity
- platform: min_max
  name: Average room pressure
  type: mean
  entity_ids:
    - sensor.aqara_sensor_1_pressure
    - sensor.aqara_sensor_2_pressure
    - sensor.aqara_sensor_3_pressure
    - sensor.aqara_sensor_4_pressure
    - sensor.aqara_sensor_5_pressure
