- platform: rest
  name: Rheinpegel
  resource: https://www.pegelonline.wsv.de/webservices/rest-api/v2/stations/KÖLN/W.json?includeCurrentMeasurement=true
  value_template: '{{ value_json.currentMeasurement.value }}'
  unit_of_measurement: cm
